package com.self.springsecurityresourceserver.security;


import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableResourceServer;
import org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.web.configurers.ResourceServerSecurityConfigurer;
import org.springframework.security.oauth2.provider.token.TokenStore;
import org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter;
import org.springframework.security.oauth2.provider.token.store.JwtTokenStore;


@EnableResourceServer
@Configuration
public class ResourceServerConfig extends ResourceServerConfigurerAdapter {

  @Override public void configure(final ResourceServerSecurityConfigurer resources) throws Exception {
    resources.tokenStore(tokenStore());
  }

  @Bean
  public TokenStore tokenStore() {
    return new JwtTokenStore(jwtAccessTokenConverter());
  }

  @Bean
  public JwtAccessTokenConverter jwtAccessTokenConverter() {
    JwtAccessTokenConverter jwtAccessTokenConverter = new JwtAccessTokenConverter();
    jwtAccessTokenConverter.setVerifierKey("-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoFamoR+MNwA/qB7RpitxNx+LsZ3" +
                                             "+MiKdhFu/QNO2U7y9QmhCnp3+8oa295wQH47jhHEh8aWmyaiNEqe/5QvU\n" +
                                             "qEMiQQ6YaygrYYfgsUUjtwY/mc8VKE+Gbb9kPNl6xHkWOKrPaZ4H8B+OU3mishU82yDZjBw6ve3FGx2TiNWnY2M9pHHFMW/b" +
                                             "+HJKx7jmJU67dreznkOwnHCjad6p48uZXAPbNLjRf6Tn55kl+6RKgEve/j4rE2pNYsbdbHUFHh8Sgnclc5SobpLKfhy" +
                                             "/44mLydt7oyZnA2f9krcC+F1LV2/R1tvmppu2TImlvFpMPvbfVS3Omz7VoiTZFe2AA4ggmwIDAQAB-----END PUBLIC KEY-----"); // public key generated by auth server
    return jwtAccessTokenConverter;
  }
}
